spring.application.name=MultipleDatabaseIntegration
# =======================
# MySQL Configuration
# =======================
spring.datasource.mysql.url=jdbc:mysql://localhost:3306/mysql_db
spring.datasource.mysql.username=root
spring.datasource.mysql.password=2001
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

# =======================
# PostgreSQL Configuration
# =======================
spring.datasource.postgres.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=2001
spring.datasource.postgres.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
